version: "3.9"

services:
  movie_db:
    image: mysql:8
    restart: always
    environment:
      - MYSQL_DATABASE=movie_db
      - MYSQL_USER=username
      - MYSQL_PASSWORD=3546
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./dbdata:/var/lib/mysql/
    ports:
      - "3307:3306"

volumes:
  db: